pool 0.ch.pool.ntp.org iburst
pool 1.ch.pool.ntp.org iburst
pool 2.ch.pool.ntp.org iburst
pool 3.ch.pool.ntp.org iburst

makestep 1.0 3
driftfile /var/lib/chrony/drift
rtcsync
logdir /var/log/chrony
log measurements tracking
