interface=uap0
ssid=@AP_SSID@
wpa_passphrase=@AP_PSK@
driver=nl80211
hw_mode=g
channel=6
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
rsn_pairwise=CCMP
auth_algs=1
macaddr_acl=0
ieee80211n=1
wmm_enabled=1
