bind-interfaces
listen-address=@AP_GATEWAY@
interface=uap0
dhcp-range=@AP_GATEWAY@,@AP_NET_PREFIX@.100,255.255.255.0,12h
address=/#/@AP_GATEWAY@
dhcp-option=3,@AP_GATEWAY@
dhcp-option=6,@AP_GATEWAY@
no-resolv
no-poll
log-dhcp
