name: Build rpi-authbox

on: [push, workflow_dispatch]

jobs:
  build:
    if: >
      contains(github.event.head_commit.message, 'ci: build') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      BR:            /home/runner/work/buildroot
      BUILD:         /home/runner/work/build
      BR2_DL_DIR:    /home/runner/work/dl
      LOGS:          /tmp
      CACHEFILE_SOURCES: ${{ github.workspace }}/.cachefile_sources

    steps:
      - name: Install base Debian packages
        run: >
          sudo
          apt-get update
          &&
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y
          gcc bash bc cpio libexpat1-dev file util-linux passwd git make
          libncurses5-dev perl pkg-config libgcc-12-dev rsync unzip util-linux
          wget 7zip

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get short revision SHA
        id: short-sha
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Vendor Go dependencies
        run: |
          cd gauthbox
          go mod vendor

      - name: Clone Buildroot
        run: git clone --depth=1 --branch=2024.08 https://gitlab.com/buildroot.org/buildroot.git $BR

      - name: Apply defconfig
        run: |
          cd rpi-authbox
          mkdir $BUILD
          make BR2_EXTERNAL=$PWD O=$BUILD -C $BR rpi3b_defconfig

      - name: Restore cached Buildroot sources
        id: restore-br-sources
        uses: actions/cache/restore@v4  # Note the /restore
        with:
          path: ${{ env.BR2_DL_DIR }}
          key: ${{ runner.os }}-br-sources-dummy
          restore-keys: |
            ${{ runner.os }}-br-sources-

      - name: Download missing Buildroot sources
        run: |
          ( cd rpi-authbox && make BR2_EXTERNAL=$PWD O=$BUILD -C $BR source 2>&1 >/dev/null )
          ( cd $BR2_DL_DIR && find -type f -not -name .lock | sort >$CACHEFILE_SOURCES )
          cat $CACHEFILE_SOURCES

      - name: Save Buildroot sources
        id: save-br-sources
        uses: actions/cache/save@v4  # Note the /save
        with:
          path: ${{ env.BR2_DL_DIR }}
          key: ${{ runner.os }}-br-sources-${{ hashFiles(env.CACHEFILE_SOURCES) }}

      - name: Restore cached host/toolchain
        id: restore-br-host
        uses: actions/cache/restore@v4  # Note the /restore
        with:
          path: ${{ env.BUILD }}
          key: ${{ runner.os }}-br-host-dummy
          restore-keys: |
            ${{ runner.os }}-br-host-

      - name: Build missing Buildroot host/toolchain
        run: |
          ( cd $BUILD && $BR/support/scripts/graph-depends --flat-list --quiet --transitive -s toolchain ) \
            | tr ' ' '\n' | grep -E '^(toolchain|host)' | sort | xargs >/tmp/host.pkgs
          cat /tmp/host.pkgs
          cd rpi-authbox && make BR2_EXTERNAL=$PWD O=$BUILD -C $BR $(cat /tmp/host.pkgs) 2>$LOGS/host.stderr >$LOGS/host.stdout

      - name: Tail logs
        if: failure()
        continue-on-error: true
        run: |
          echo stdout:
          tail -n 300 $LOGS/host.stdout
          echo
          echo stderr:
          tail -n 300 $LOGS/host.stderr

      - name: Save cached host/toolchain
        id: save-br-host
        uses: actions/cache/save@v4  # Note the /save
        with:
          path: ${{ env.BUILD }}
          key: ${{ runner.os }}-br-host-${{ hashFiles(env.CACHEFILE_SOURCES) }}

      - name: Build everything
        run: |
          cd rpi-authbox
          make BR2_EXTERNAL=$PWD O=$BUILD -C $BR rpi-authbox.7z \
            2>$LOGS/build.stderr >$LOGS/build.stdout

      - name: Tail logs
        if: failure()
        continue-on-error: true
        run: |
          echo stdout:
          tail -n 300 $LOGS/build.stdout
          echo
          echo stderr:
          tail -n 300 $LOGS/build.stderr

      - name: Upload rpi-authbox
        uses: actions/upload-artifact@v4
        with:
          name: rpi-authbox
          path: ${{ env.BUILD }}/rpi-authbox

      - name: Upload rpi-authbox.7z
        uses: actions/upload-artifact@v4
        with:
          name: rpi-authbox.7z
          path: ${{ env.BUILD }}/rpi-authbox.7z

      - name: Create release
        continue-on-error: true
        uses: softprops/action-gh-release@cd8b57e57218a24af14e307ad8491ec133804ef1
        with:
          draft: true
          name: rpi-authbox-${{ steps.short-sha.outputs.sha }}
          files: ${{ env.BUILD }}/rpi-authbox.7z
          fail_on_unmatched_files: true
