name: Build rpi-authbox

on: [push, workflow_dispatch]

jobs:
  build:
    if: >
      contains(github.event.head_commit.message, 'ci: build-rpi-authbox') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      BR:            /home/runner/work/buildroot
      BUILD:         /home/runner/work/build
      BR2_DL_DIR:    /home/runner/work/dl
      LOGS:          /tmp
      RATELIMIT:     1
      CACHEFILE_SOURCES: ${{ github.workspace }}/.cachefile_sources

    steps:
      - name: Install base Debian packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: >
          sudo apt-get update
          &&
          sudo apt-get install --no-install-recommends --assume-yes
          gcc bash bc cpio libexpat1-dev file util-linux passwd git make
          libncurses5-dev perl pkg-config libgcc-12-dev rsync unzip util-linux
          wget 7zip pv

      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Get short revision SHA
        id: short-sha
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Vendor Go dependencies
        run: |
          cd gauthbox
          go mod vendor

      - name: Clone Buildroot
        run: git clone --depth=1 --branch=2026.02 https://gitlab.com/buildroot.org/buildroot.git $BR

      - name: Apply defconfig
        run: |
          cd rpi-authbox
          mkdir $BUILD
          make BR2_EXTERNAL=$PWD O=$BUILD -C $BR rpi3b_defconfig

      - name: Restore cached Buildroot sources
        id: restore-br-sources
        uses: actions/cache/restore@v4  # Note the /restore
        with:
          path: ${{ env.BR2_DL_DIR }}
          key: ${{ runner.os }}-br-sources-dummy
          restore-keys: |
            ${{ runner.os }}-br-sources-

      - name: Download missing Buildroot sources
        run: |
          ( cd rpi-authbox && make BR2_EXTERNAL=$PWD O=$BUILD -C $BR source 2>&1 >/dev/null )
          ( cd $BR2_DL_DIR && find -type f -not -name .lock | sort >$CACHEFILE_SOURCES )
          cat $CACHEFILE_SOURCES

      - name: Save Buildroot sources
        id: save-br-sources
        uses: actions/cache/save@v4  # Note the /save
        with:
          path: ${{ env.BR2_DL_DIR }}
          key: ${{ runner.os }}-br-sources-${{ hashFiles(env.CACHEFILE_SOURCES) }}

      - name: Restore cached host/toolchain
        id: restore-br-host
        uses: actions/cache/restore@v4  # Note the /restore
        with:
          path: ${{ env.BUILD }}
          key: ${{ runner.os }}-br-host-dummy
          restore-keys: |
            ${{ runner.os }}-br-host-

      - name: Build missing Buildroot host/toolchain
        run: |
          ( cd $BUILD && $BR/support/scripts/graph-depends --flat-list --quiet --transitive -s toolchain ) \
            | tr ' ' '\n' | grep -E '^(toolchain|host)' | sort | xargs >/tmp/host.pkgs
          cat /tmp/host.pkgs
          cd rpi-authbox && make BR2_EXTERNAL=$PWD O=$BUILD -C $BR $(cat /tmp/host.pkgs) 2>&1 >$LOGS/host

      - name: Tail host logs
        if: failure()
        continue-on-error: true
        run: |
          echo stdout/stderr for host/toolchain:
          tail -n 300 $LOGS/host

      - name: Save cached host/toolchain
        id: save-br-host
        uses: actions/cache/save@v4  # Note the /save
        with:
          path: ${{ env.BUILD }}
          key: ${{ runner.os }}-br-host-${{ hashFiles(env.CACHEFILE_SOURCES) }}

      - name: Build everything
        run: |
          cd rpi-authbox
          make BR2_EXTERNAL=$PWD O=$BUILD -C $BR rpi-authbox.7z 2>&1 >$LOGS/build

      - name: Tail build logs
        if: failure()
        continue-on-error: true
        run: |
          echo stdout/stderr for build:
          tail -n 300 $LOGS/build

      - name: Upload rpi-authbox
        uses: actions/upload-artifact@v7
        with:
          name: rpi-authbox
          path: ${{ env.BUILD }}/rpi-authbox

      - name: Upload rpi-authbox.7z
        uses: actions/upload-artifact@v7
        with:
          name: rpi-authbox.7z
          path: ${{ env.BUILD }}/rpi-authbox.7z

      - name: Create release
        continue-on-error: true
        uses: softprops/action-gh-release@cd8b57e57218a24af14e307ad8491ec133804ef1
        with:
          draft: true
          name: rpi-authbox-${{ steps.short-sha.outputs.sha }}
          files: ${{ env.BUILD }}/rpi-authbox.7z
          fail_on_unmatched_files: true

  build_usb_gadget:
    runs-on: ubuntu-26.04-arm
    if: >
      contains(github.event.head_commit.message, 'ci: build-usb-gadget') || github.event_name == 'workflow_dispatch'
    name: build usb gadget authbox for RPi Zero 2 W

    steps:
      - uses: actions/checkout@v7

      - name: Install base Debian packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: >
          sudo apt-get update
          &&
          sudo apt-get install --no-install-recommends --assume-yes
          podman age dosfstools mtools parted

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          extra_nix_config: sandbox = true

      - name: Build
        working-directory: wifi-usb
        run: |
          cat <<EOF > .envrc.local
            export WIFI_SSID=${{ secrets.WIFI_SSID }}
            export WIFI_PSK=${{ secrets.WIFI_PSK }}
            export CONFIG_URL=${{ secrets.CONFIG_URL }}
            export ROOT_PSWD=${{ secrets.ROOT_PSWD }}
            export RCLONE_CONFIG=/media/mmcblk0p1/rclone.conf
          EOF
          source <(sed '/use flake/d' .envrc)
          make

      - name: Encrypt
        working-directory: wifi-usb/out
        env:
          RECIPIENT: age1kpjkw5fe2p3l7ty77l3wqj927mdcagcla5gqf9fydx5h9djlhucqhkgh8s
        run: |
          age -e -r "$RECIPIENT" -o sdcard.img.enc               sdcard.img
          age -e -r "$RECIPIENT" -o dropportal.apkovl.tar.gz.enc dropportal.apkovl.tar.gz

      - name: Upload usb_gadget_authbox
        uses: actions/upload-artifact@v7
        with:
          name: usb_gadget_authbox
          path: |
            wifi-usb/out/sdcard.img.enc
            wifi-usb/out/dropportal.apkovl.tar.gz.enc

  build_authbox_config:
    runs-on: ubuntu-latest
    name: build authbox_config for x86_64

    steps:
      - uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: gauthbox/go.mod
          cache-dependency-path: gauthbox/go.sum

      - name: Build
        run: cd gauthbox && go build -v -o authbox_config ./cmd/config

      - name: Upload authbox_config
        uses: actions/upload-artifact@v7
        with:
          name: authbox_config
          path: gauthbox/authbox_config
