name: Build rpi-authbox

on: [push]

jobs:
  build:
    if: >
      contains(github.event.head_commit.message, 'ci: build')
    runs-on: ubuntu-latest
    env:
      BR:         /home/runner/work/buildroot
      BUILD:      /home/runner/work/build
      BR2_DL_DIR: /home/runner/work/build/dl

    steps:
      - name: Install base Debian packages
        run: >
          sudo
          apt-get update
          &&
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y
          gcc bash bc cpio libexpat1-dev file util-linux passwd git make
          libncurses5-dev perl pkg-config libgcc-12-dev rsync unzip util-linux
          wget 7zip

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Clone Buildroot
        run: git clone --depth=1 --branch=2024.08 https://gitlab.com/buildroot.org/buildroot.git $BR

      - name: Apply defconfig
        run: |
          cd rpi-authbox
          mkdir $BUILD
          make BR2_EXTERNAL=$PWD O=$BUILD -C $BR rpi3b_defconfig

      - name: Restore cached Buildroot sources
        id: cache-br-sources
        uses: actions/cache@v4
        with:
          path: ${{ env.BR2_DL_DIR }}
          key: ${{ runner.os }}-br-sources-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-br-sources-

      - name: Download missing Buildroot sources
        run: |
          cd rpi-authbox
          make BR2_EXTERNAL=$PWD O=$BUILD -C $BR source

      - name: Build
        run: |
          cd rpi-authbox
          make BR2_EXTERNAL=$PWD O=$BUILD -C $BR rpi-authbox.7z

      - name: Upload rpi-authbox.7z
        uses: actions/upload-artifact@v4
        with:
          name: rpi-authbox.7z
          path: ${{ env.BUILD }}/rpi-authbox.7z
